
import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;

public class Reversi extends javax.swing.JFrame {

    int player = 1;
    int x = 25;
    int y = 25;

    public Reversi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(new java.awt.GridLayout(4, 4, 1, 1));

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel1MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel1);

        jLabel2.setBackground(java.awt.Color.darkGray);
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel2MouseReleased(evt);
            }
        });
        jPanel1.add(jLabel2);

        jLabel3.setBackground(java.awt.Color.lightGray);
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel3);

        jLabel4.setBackground(java.awt.Color.darkGray);
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel4);

        jLabel5.setBackground(java.awt.Color.darkGray);
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel5);

        jLabel6.setBackground(java.awt.Color.lightGray);
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Graphics g = jLabel6.getGraphics();
        g.setColor(Color.BLACK);
        g.fillOval(0, 0, jLabel6.getWidth(), jLabel6.getHeight());
        jPanel1.add(jLabel6);

        jLabel7.setBackground(java.awt.Color.darkGray);
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel7);

        jLabel8.setBackground(java.awt.Color.lightGray);
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel8);

        jLabel9.setBackground(java.awt.Color.lightGray);
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel9);

        jLabel10.setBackground(java.awt.Color.darkGray);
        jLabel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel10);

        jLabel11.setBackground(java.awt.Color.lightGray);
        jLabel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel11);

        jLabel12.setBackground(java.awt.Color.darkGray);
        jLabel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel12);

        jLabel13.setBackground(java.awt.Color.darkGray);
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel13);

        jLabel14.setBackground(java.awt.Color.lightGray);
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel14);

        jLabel15.setBackground(java.awt.Color.darkGray);
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel15);

        jLabel16.setBackground(java.awt.Color.lightGray);
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(jLabel16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseReleased
        if (player == 1) {
            botaoBranco(evt);
            player = 2;
        } else {
            botaoPreto(evt);
            player = 1;
        }
    }//GEN-LAST:event_jLabel2MouseReleased

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseReleased
        if (player == 1) {
            botaoBranco(evt);
            player = 2;
        } else {
            botaoPreto(evt);
            player = 1;
        }
    }//GEN-LAST:event_jLabel1MouseReleased

    public void botaoPreto(MouseEvent evt) {
        int objX = evt.getLocationOnScreen().x;
        int objY = evt.getLocationOnScreen().y;
        System.out.println("X = " + objX);
        System.out.println("Y = " + objY);

        if ((objX >= 3 && objY >= 8) && (objX <= 612 && objY <= 265)) {
            Graphics b1 = jLabel1.getGraphics();
            b1.setColor(Color.BLACK);
            b1.fillOval(x, y, 100, 100);
        } else if (evt.getButton() == MouseEvent.BUTTON2) {
            System.out.println(evt.getLocationOnScreen());
            Graphics b1 = jLabel2.getGraphics();
            b1.setColor(Color.BLACK);
            b1.fillOval(x, y, 100, 100);
        }
    }
//    public boolean comparacao(MouseEvent evt) {
//        int objX = evt.getLocationOnScreen().x;
//        int objY = evt.getLocationOnScreen().y;
//        return (objX >= 3 && objY >= 8) && (objX <= 612 && objY <= 265);
//    }
//    

    public void botaoBranco(MouseEvent evt) {
        int objX = evt.getLocationOnScreen().x;
        int objY = evt.getLocationOnScreen().y;
        System.out.println("X = " + objX);
        System.out.println("Y = " + objY);
        if ((objX >= 3 && objY >= 8) && (objX <= 612 && objY <= 265)) {
            Graphics b1 = jLabel1.getGraphics();
            b1.setColor(Color.BLACK);
            b1.fillOval(x, y, 100, 100);
        } else if (evt.getButton() == MouseEvent.BUTTON2) {
            Graphics b1 = jLabel2.getGraphics();
            b1.setColor(Color.BLACK);
            b1.fillOval(x, y, 100, 100);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reversi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reversi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
