/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula0526.interfacegrafica;

/**
 *
 * @author joaof
 */
public class TelaSorvete extends javax.swing.JFrame {

    /**
     * Creates new form TelaSorvete
     */
    
    private int total;
    
    public TelaSorvete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rdbChocolate = new javax.swing.JRadioButton();
        rdbMorango = new javax.swing.JRadioButton();
        rdbPistache = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        ckbChocolate = new javax.swing.JCheckBox();
        ckbChocolate.setEnabled(false);
        ckbCaramelo = new javax.swing.JCheckBox();
        ckbCaramelo.setEnabled(false);
        ckbAmendoas = new javax.swing.JCheckBox();
        ckbAmendoas.setEnabled(false);
        jPanel3 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sabores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        rdbChocolate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbChocolate.setText("CHOCOLATE - R$ 10,00");
        rdbChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbChocolateActionPerformed(evt);
            }
        });

        rdbMorango.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbMorango.setText("MORANGO - R$ 5,00");
        rdbMorango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbMorangoActionPerformed(evt);
            }
        });

        rdbPistache.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdbPistache.setText("PISTACHE - R$ 15,00");
        rdbPistache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPistacheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbChocolate, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(rdbMorango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbPistache, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rdbChocolate)
                .addGap(16, 16, 16)
                .addComponent(rdbMorango)
                .addGap(16, 16, 16)
                .addComponent(rdbPistache)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coberturas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        ckbChocolate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbChocolate.setText("CHOCOLATE - R$ 3,00");
        ckbChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbChocolateActionPerformed(evt);
            }
        });

        ckbCaramelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbCaramelo.setText("CARAMELO - R$ 4,00");
        ckbCaramelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbCarameloActionPerformed(evt);
            }
        });

        ckbAmendoas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckbAmendoas.setText("AMENDOAS - R$ 10,00");
        ckbAmendoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbAmendoasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckbChocolate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbCaramelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ckbAmendoas, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ckbChocolate)
                .addGap(20, 20, 20)
                .addComponent(ckbCaramelo)
                .addGap(20, 20, 20)
                .addComponent(ckbAmendoas)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdbChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbChocolateActionPerformed
        
        ckbChocolate.setEnabled(true);
        ckbCaramelo.setEnabled(true);
        ckbAmendoas.setEnabled(true);
        
        if (rdbChocolate.isSelected()) {
            rdbMorango.setSelected(false);
            rdbPistache.setSelected(false);
            ckbChocolate.setSelected(false);
            total = 10;
        }
        lblTotal.setText("Total: R$" + total);
    }//GEN-LAST:event_rdbChocolateActionPerformed

    private void rdbMorangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbMorangoActionPerformed
        
        ckbChocolate.setEnabled(true);
        ckbCaramelo.setEnabled(true);
        ckbAmendoas.setEnabled(true);
        
        if(rdbMorango.isSelected()) {
            rdbChocolate.setSelected(false);
            rdbPistache.setSelected(false);
            total = 5;
        }
        lblTotal.setText("Total: R$" + total);
    }//GEN-LAST:event_rdbMorangoActionPerformed

    private void rdbPistacheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPistacheActionPerformed
        
        ckbChocolate.setEnabled(true);
        ckbCaramelo.setEnabled(true);
        ckbAmendoas.setEnabled(true);
        
        if(rdbPistache.isSelected()) {
            rdbChocolate.setSelected(false);
            rdbMorango.setSelected(false);
            total = 15;
        }
        lblTotal.setText("Total: R$" + total);
    }//GEN-LAST:event_rdbPistacheActionPerformed

    private void ckbChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbChocolateActionPerformed
        
        if(ckbChocolate.isSelected()) {
            total += 3;
        }else {
            total -= 3;
        } 
        
        lblTotal.setText("Total: R$" + total);
    }//GEN-LAST:event_ckbChocolateActionPerformed

    private void ckbCarameloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbCarameloActionPerformed
        
        if(ckbCaramelo.isSelected()) {
            total += 4;
        }else {
            total -= 4;
        }
        lblTotal.setText("Total: R$" + total);
    }//GEN-LAST:event_ckbCarameloActionPerformed

    private void ckbAmendoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbAmendoasActionPerformed
        
        if(ckbAmendoas.isSelected()) {
            total += 10;
        }else {
            total -= 10;
        }
        lblTotal.setText("Total: R$" + total);
    }//GEN-LAST:event_ckbAmendoasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSorvete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSorvete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSorvete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSorvete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSorvete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbAmendoas;
    private javax.swing.JCheckBox ckbCaramelo;
    private javax.swing.JCheckBox ckbChocolate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rdbChocolate;
    private javax.swing.JRadioButton rdbMorango;
    private javax.swing.JRadioButton rdbPistache;
    // End of variables declaration//GEN-END:variables
}
