
import java.math.BigDecimal;
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author joaof
 */
public class TelaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtA = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        lblEquacao = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        lblZeroDois = new javax.swing.JLabel();
        lblZeroUm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coeficiente a:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        txtC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coeficiente c:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCMousePressed(evt);
            }
        });

        txtB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coeficiente b:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblEquacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEquacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Equação:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblZeroDois.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblZeroDois.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZeroDois.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Segundo Zero:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblZeroUm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblZeroUm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblZeroUm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Primeiro Zero", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCalcular)
                        .addGap(51, 51, 51)
                        .addComponent(btnLimpar)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEquacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblZeroUm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblZeroDois, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpar)
                    .addComponent(btnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEquacao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblZeroDois, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblZeroUm, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMouseClicked

    }//GEN-LAST:event_txtCMouseClicked

    private void txtCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCMousePressed

    }//GEN-LAST:event_txtCMousePressed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtA.setText(null);
        txtB.setText(null);
        txtC.setText(null);
        lblEquacao.setText(null);
        lblZeroUm.setText(null);
        lblZeroDois.setText(null);
    }//GEN-LAST:event_btnLimparActionPerformed


    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double a = Double.parseDouble(txtA.getText());
        double b = Double.parseDouble(txtB.getText());
        double c = Double.parseDouble(txtC.getText());

        // MOSTRANDO NA TELA
        if (a != 0) { // PARA COEFICIENTE a DIFERENTE DE ZERO
            if (b > 0) {
                if (c > 0) {
                    lblEquacao.setText(Double.toString(a) + "x² + "
                            + Double.toString(b) + "x + "
                            + Double.toString(c) + " = 0");
                } else if (c < 0) {
                    lblEquacao.setText(Double.toString(a) + "x² + "
                            + Double.toString(b) + "x - "
                            + Double.toString(Math.abs(c)) + " = 0");
                } else {
                    lblEquacao.setText(Double.toString(a) + "x² + "
                            + Double.toString(b) + "x = 0");
                }

            } else if (b == 0) {
                if (c > 0) {
                    lblEquacao.setText(Double.toString(a) + "x² + "
                            + Double.toString(c) + " = 0");
                } else if (c == 0) {
                    lblEquacao.setText(Double.toString(a) + "x² = 0");
                } else {
                    lblEquacao.setText(Double.toString(a) + "x² - "
                            + Double.toString(Math.abs(c)) + " = 0");
                }
            } else {
                if (c > 0) {
                    lblEquacao.setText(Double.toString(a) + "x² - "
                            + Double.toString(Math.abs(b)) + "x + "
                            + Double.toString(c) + " = 0");
                } else if (c < 0) {
                    lblEquacao.setText(Double.toString(a) + "x² - "
                            + Double.toString(Math.abs(b)) + "x - "
                            + Double.toString(Math.abs(c)) + " = 0");
                } else {
                    lblEquacao.setText(Double.toString(a) + "x² - "
                            + Double.toString(Math.abs(b)) + "x = 0");
                }
            }
        } else { // PARA COEFICIENTE a IGUAL A ZERO.
            lblZeroDois.setText(null);
            if (b != 0) {
                if (c > 0) {
                    lblEquacao.setText(Double.toString(b) + "x + "
                            + Double.toString(c) + " = 0");
                } else if (c < 0) {
                    lblEquacao.setText(Double.toString(b) + "x - "
                            + Double.toString(Math.abs(c)) + " = 0");
                } else {
                    lblEquacao.setText(Double.toString(b) + "x = 0");
                }
            } else {
                lblEquacao.setText("Pelo menos um coeficiente com x");
            }
        }

        //CALCULANDO OS ZEROS DA EQUAÇÃO
        if (a != 0) { // PARA EQUAÇÕES DE 2° GRAU
            double delta = Math.pow(b, 2) - 4 * a * c;
            if (Math.sqrt(delta) >= 0) {
                double primeiroZeroDouble = ((-b + Math.sqrt(delta)) / (2 * a)) * 100;
                int primeiroZeroInt = (int) primeiroZeroDouble;
                double primeiroZero = (double) primeiroZeroInt / 100;

                double segundoZeroDouble = ((-b - Math.sqrt(delta)) / (2 * a)) * 100;
                int segundoZeroInt = (int) segundoZeroDouble;
                double segundoZero = (double) segundoZeroInt / 100;

                lblZeroUm.setText(Double.toString(primeiroZero));
                lblZeroDois.setText(Double.toString(segundoZero));

            } else {
                // CÁLCULO DOS ZEROS DA EQUAÇÃO 2° GRAU
                double realDouble = (-b / (2 * a)) * 100;
                double imaginarioDouble = Math.sqrt(Math.abs(delta)) / (2 * a);
                
                // ARREDONDANDO PARA 2 CASAS DECIMAIS
                int realInt = (int) realDouble;
                double real = (double) realInt / 100;
                
                int imaginarioInt = (int) imaginarioDouble;
                double imaginario = (double) imaginarioInt / 100;
                
                // CONVERTENDO PARA STRING
                String primeiroZero = Double.toString(real) + " + "
                        + Double.toString(imaginario) + "i";
                String segundoZero = Double.toString(real) + " + "
                        + Double.toString(imaginario) + "i";

                // PRINTANDO NO LABEL
                lblZeroUm.setText(primeiroZero);
                lblZeroDois.setText(segundoZero);
            }

        } else if (a == 0) { // PARA EQUAÇÕES DE PRIMEIRO GRAU
            if (b == 0) {
                lblZeroUm.setText(null);
                lblZeroDois.setText(null);
            } else {
                double unicoZero = -c / b;
                lblZeroUm.setText(Double.toString(unicoZero));
            }
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel lblEquacao;
    private javax.swing.JLabel lblZeroDois;
    private javax.swing.JLabel lblZeroUm;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables
}
